eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driverClassName: org.h2.Driver
#     username: sa
#     password: password
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     defer-datasource-initialization: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver


    
