spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: resource
          uri: lb://resource-service
          predicates:
            - Path=/gateway-service/**
          filters:
            - StripPrefix=1
        - id: database
          uri: lb://database-service
          predicates:
            - Path=/gateway-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
